---
apiVersion: beat.k8s.elastic.co/v1beta1
kind: Beat
metadata:
  name: metricbeat-ods
  namespace: ods
spec:
  type: metricbeat
  version: 8.13.4
  elasticsearchRef:
    name: elasticsearch
    namespace: elastic
  kibanaRef:
    name: kibana
    namespace: elastic
  config:
    metricbeat:
      modules:
      - module: mssql
        metricsets:
          - transaction_log
          - performance
        hosts:
          - sqlserver://sa@mssql-deployment.ods.svc
        password: ${MSSQL_SA_PASSWORD}
    processors:
    - add_cloud_metadata: {}
    - add_host_metadata: {}
  deployment:
    replicas: 1
    podTemplate:
      spec:
        serviceAccountName: metricbeat
        automountServiceAccountToken: true
        containers:
        - args:
          - -e
          - -c
          - /etc/beat.yml
          - -system.hostfs=/hostfs
          name: metricbeat
          securityContext:
            runAsUser: 0
            privileged: true
          env:
          - name: NODE_NAME
            valueFrom:
              fieldRef:
                fieldPath: spec.nodeName
          - name: MSSQL_SA_PASSWORD
            valueFrom:
              secretKeyRef:
                name: mssql
                key: MSSQL_SA_PASSWORD
          resources:
            limits:
              memory: 256Mi
            requests:
              cpu: 200m
              memory: 128Mi
        dnsPolicy: ClusterFirstWithHostNet
        hostNetwork: true
        terminationGracePeriodSeconds: 30
