---
apiVersion: v1
kind: Namespace
metadata:
  name: ods
  labels:
    kubernetes.io/metadata.name: ods
    openshift.io/cluster-monitoring: "true"
  annotations:
    openshift.io/description: APS OCP Demo of SQL Server for ODS
    openshift.io/display-name: Demo ODS
spec:
  finalizers:
    - kubernetes
---
apiVersion: v1
kind: Secret
metadata:
  name: mssql
  namespace: ods
type: Opaque
data:
  MSSQL_SA_PASSWORD: TXlDMG05bCZ4UEBzc3cwcmQ=
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mssql-data
  namespace: ods
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 8Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mssql-deployment
  namespace: ods
spec:
  replicas: 1
  selector:
     matchLabels:
       app: mssql
  template:
    metadata:
      annotations:
        co.elastic.logs/enabled: true
        co.elastic.logs/module: mssql
      labels:
        app: mssql
    spec:
      terminationGracePeriodSeconds: 30
      hostname: mssqlinst
      securityContext:
        fsGroupChangePolicy: OnRootMismatch
      containers:
      - name: mssql
        image: mcr.microsoft.com/mssql/rhel/server:2019-CU23-rhel-8.7
        resources:
          requests:
            memory: "2G"
            cpu: "2000m"
          limits:
            memory: "2G"
            cpu: "2000m"
        ports:
        - containerPort: 1433
        securityContext:
          capabilities:
            add:
            - NET_BIND_SERVICE
        env:
        - name: MSSQL_PID
          value: "Developer"
        - name: ACCEPT_EULA
          value: "Y"
        - name: MSSQL_SA_PASSWORD
          valueFrom:
            secretKeyRef:
              name: mssql
              key: MSSQL_SA_PASSWORD
        volumeMounts:
        - name: mssqldb
          mountPath: /var/opt/mssql
      volumes:
      - name: mssqldb
        persistentVolumeClaim:
          claimName: mssql-data
---
apiVersion: v1
kind: Service
metadata:
  name: mssql-deployment
  namespace: ods
spec:
  selector:
    app: mssql
  ports:
    - protocol: TCP
      port: 1433
      targetPort: 1433
  type: LoadBalancer
